### ISSUE TITLE
Question and  maybe issue on format video width and height?

### ISSUE THREAD

**Issue by videmort** [opentok/opentok-cordova-samples#11]
It's possible to change between cameras any function to do that?
And mute/unmute?
How can I change the width and height of the video. I tried via css but nope ;) (I attach one image on iphone X)
![image1](https://user-images.githubusercontent.com/11390548/36816492-37ac2792-1cde-11e8-9b55-331dd4b24242.png)

**Comment by mark-veenstra** [comment]
Same answer as: https://github.com/opentok/cordova-plugin-opentok/issues/47

**Comment by msach22** [comment]
Closing b/c duplicate
