### ISSUE TITLE
Could not find method implementation() for arguments [directory 'libs'] on object of type org .gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by ayubUOL** [opentok/opentok-cordova-samples#19]
Trying to build APK file for it but facing error in opentok plugin gradle file.
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.opentok.android:opentok-android-sdk:2.15.1'
} `

**Comment by pareshgami** [comment]
Anyone else facing the same issue? @ayubUOL  Why you close this issue? Got solution? Please share it.

**Comment by VrVinay** [comment]
Even I am facing the same issue.
Can you tell me what you did to solve it

**Comment by pareshgami** [comment]
I think changing version of that make it resolve.

`cordova plugin add cordova-plugin-opentok@3.2.2 --save`
