### ISSUE TITLE
Cordova android basic video not working

### ISSUE THREAD

**Issue by alaghusun60** [opentok/opentok-cordova-samples#23]
browser to android(cordova) working in one machine.  cordova android to android not working. i got output as following
 domId exists but properties width or height is not specified opentok.js:519
 width: 600 and height: 0 for domId publisher, and top: 0, left: 0 opentok.js:521
JS Lib: creating publisher -  
Object
 opentok.js:317
JS: Objects being updated in TBUpdateObjects opentok.js:248
JS: Object updated opentok.js:253
JS sessionId: TBPublisher opentok.js:255
Received Event: deviceready 

I tested in android
4.4.2 
8.1.0

**Comment by alaghusun60** [comment]
i got error in  android 4.4.2 in following line
 console.log(`Stream ${event.stream.name} ended because ${event.reason}.`); 
so i coment this still video not working

**Comment by msach22** [comment]
@alaghusun60 Are you getting any other errors? Have you checked out the [Inspector tool](https://tokbox.com/developer/tools/inspector/) to see if you're getting any errors in the session? Could you please also share which version of the Cordova plugin you're using?

**Comment by alaghusun60** [comment]
actually its working somewhere good in cordova android to browser. android to android cordova version not good. condroid android to browser itself we dont get opposition video stream some times. We dont get any error

**Comment by alaghusun60** [comment]
actually native android version look like stable. cordova version we required stable version

**Comment by msach22** [comment]
Glad to hear it's working @alaghusun60. I'm going to go ahead and close the issue
