### ISSUE TITLE
Refused to load the image 'android-webview-video-poster

### ISSUE THREAD

**Issue by kerloom** [opentok/opentok-cordova-samples#7]
Getting the following error when running the Basic Video Chat on android:
`Refused to load the image 'android-webview-video-poster:default_video_poster/6528159162652968060' because it violates the following Content Security Policy directive: "img-src 'self' data: content:".`

**Comment by msach22** [comment]
@kerloom I just cloned the repo and ran a quick test and am not able to replicate this issue. Could you please confirm that you followed the installation instructions? https://github.com/opentok/opentok-cordova-samples#note-please-make-sure-to-run-the-commands-in-the-same-order-as-below

**Comment by kerloom** [comment]
@msach22 
I just figured this out. I tried on two different devices (4.4 and 5.0 android) and changed first the directive to `img-src *` and that did the trick for Android 4.4. For Android 5.0 I changed the meta directive to `<meta http-equiv="Content-Security-Policy" content="default-src * gap:; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src *; img-src * data: blob: android-webview-video-poster:; style-src * 'unsafe-inline';">` and it seemed to do the trick.

**Comment by HaiderSahib** [comment]
I have the same error on Android 6.0.1. Adding android-webview-video-poster: removed the error but still no video. The publisher element show black box with play icon

**Comment by msach22** [comment]
@HaiderSahib are you using `opentok.js` file that's provided by the plugin or the OpenTok JS SDK

**Comment by HaiderSahib** [comment]
I am trying to run the Basic-Video-Chat sample and I followed the steps one by one

**Comment by msach22** [comment]
@HaiderSahib can you attach a screenshot of what you're seeing?

**Comment by HaiderSahib** [comment]
![screenshot_20180227-124226](https://user-images.githubusercontent.com/909503/36744937-15cc9ed6-1bbc-11e8-88dd-d062e6605d2d.png)

**Comment by HaiderSahib** [comment]
this is when I add android-webview-video-poster:. With the original code, it just a black box

**Comment by mark-veenstra** [comment]
What does the console logging say? Any errors?

**Comment by HaiderSahib** [comment]
@mark-veenstra When adding "android-webview-video-poster:" (the above screenshot) to meta tag there is no error as shown in the following screenshot from chrome inspect
<img width="1354" alt="screen shot 2018-02-28 at 10 00 43 am" src="https://user-images.githubusercontent.com/909503/36794547-a21798f2-1c6e-11e8-93d4-76b378abf84b.png">

**Comment by HaiderSahib** [comment]
For the original code, the error is shown below:
<img width="1352" alt="screen shot 2018-02-28 at 9 55 41 am" src="https://user-images.githubusercontent.com/909503/36794606-ca9140bc-1c6e-11e8-941b-da5bccb769b1.png">

**Comment by HaiderSahib** [comment]
I am using a real device with Android 6.0.1

**Comment by mark-veenstra** [comment]
I just tested from a clean clone and all works. Even with the poster error al just works, what I did:
* Clean clone of this repository
* After the clean I entered the dir `Basic-Video-Chat`
* install depedencies: `npm install`
* `cordova platform add android`
* Edited `www/js/config.js` with correct information
* Connected my Android device to PC/laptop with USB debugging and run `cordova run android`
* APK builds and gets pushed to the device. And I see the video.

![selectie_002](https://user-images.githubusercontent.com/8984015/36795752-1b83dd74-1ca4-11e8-8e6b-cbede8f535e5.png)

**Comment by mark-veenstra** [comment]
@HaiderSahib If I do not enter any credentials in the file `www/js/config.js` I also get the same result as you. Are you sure you enter the correct details in that file?

**Comment by mark-veenstra** [comment]
@msach22 https://github.com/opentok/cordova-plugin-opentok/blob/master/src/js/OT.coffee#L19 only checks if `sessionId` equals `null`. See this result in `opentok.js`: https://github.com/opentok/cordova-plugin-opentok/blob/master/www/opentok.js#L9.

An empty `sessionId` does not equal `null` so the error is not thown when people mis-configure it.

**Comment by HaiderSahib** [comment]
@mark-veenstra I am not sure if I am generating the correct credentials. I am using the link https://tokbox.com/developer/tools/playground/ to generate the session ID. I am using an API key from a standard project that I created. Below is a screenshot of creating session form (I am not sure what to put in "Connection data" so I left it blank)

<img width="926" alt="screen shot 2018-02-28 at 10 36 33 am" src="https://user-images.githubusercontent.com/909503/36796476-a6c9992c-1c73-11e8-886b-3ddb4836185b.png">

**Comment by mark-veenstra** [comment]
You need to create a session and a token and all of this information should be added to the [`www/js/config.js`](https://github.com/opentok/opentok-cordova-samples/blob/master/Basic-Video-Chat/www/js/config.js) file.

You can also manually check the same credentials here: https://tokbox.com/tools/credential-validator/

**Comment by HaiderSahib** [comment]
From the link you posted, it seems everything is OK with the credentials
<img width="643" alt="screen shot 2018-02-28 at 10 45 18 am" src="https://user-images.githubusercontent.com/909503/36796913-aace5d2c-1c74-11e8-984a-4032acb2fc76.png">

**Comment by HaiderSahib** [comment]
here is my config.js:
// Set Credentials
var apiKey = '46066742';
var sessionId = '1_MX40NjA2Njc0Mn5-MTUxOTc1NTM0ODMzOX5JMnd2VzdaRlh1bDBIQndJbzB4UWxBaUN-fg';
var token = 'T1==cGFydG5lcl9pZD00NjA2Njc0MiZzZGtfdmVyc2lvbj1kZWJ1Z2dlciZzaWc9YzJiOWQyNGVmMGIzNTRlYzE3YmE0ZTkzMzllMTE1YTY4MmEzNGYzZDpzZXNzaW9uX2lkPTFfTVg0ME5qQTJOamMwTW41LU1UVXhPVGMxTlRNME9ETXpPWDVKTW5kMlZ6ZGFSbGgxYkRCSVFuZEpiekI0VVd4QmFVTi1mZyZjcmVhdGVfdGltZT0xNTE5NzU1MzQ4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTE1MTk3NTUzNDguMzQyNTIxNzg1MDU0MyZleHBpcmVfdGltZT0xNTIyMzQ3MzQ4';

**Comment by mark-veenstra** [comment]
@HaiderSahib Hmm that is quite strange. Then I would believe it should work.
Any errors with `adb logcat '*:E'` or any output with `adb logcat -s OTPlugin`?

**Comment by msach22** [comment]
@mark-veenstra thanks for helping debug. @HaiderSahib are you running `cordova prepare android` and then running it on your device each time you make a change in your html/js/css files?

**Comment by mark-veenstra** [comment]
@HaiderSahib Just tested it with you provided credentials in `config.js` and it works fine at my side when I build it and test it.

**Comment by HaiderSahib** [comment]
@mark-veenstra it is working now, the problem was from the internet connection. The device is connecting to Starbucks WiFi. For some reason, all other websites are working but the connection for the plugin was refused. I restarted the device and it is working now. 
Thanks

**Comment by mark-veenstra** [comment]
Yeah the network should allow websockets turn and stun at least. If it is restricted even more check:
https://tokbox.com/developer/guides/restricted-networks/

**Comment by msach22** [comment]
Closing this issue, but if this issue still persists, please re-open!
