### ISSUE TITLE
Publisher video not appending inside div

### ISSUE THREAD

**Issue by kerloom** [opentok/opentok-cordova-samples#8]
I have been battling trying to get the divs in place and size in my app. I finally noticed that the video being injected for the publisher is not getting inside the target div, but rather as a child of body. I replicated this in the basic-video-chat app. Try adding custom css.

**Comment by kerloom** [comment]
I found out the error. Line 45 of index.js initialized the publisher with the api key, however it is not required. It should be instead (just as the readme states):
`var publisher = OT.initPublisher( 'publisher');`

**Comment by msach22** [comment]
@kerloom thanks for catching the issue. The old plugin used to require the `apiKey` as the first param for the `initPublisher` method.
